bot.token: '6616805676:AAHO3d7zQpuZ4IcMInVU9jNXKCy2H-dtH2M'
bot.name: 'QDuty_bot'

spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:postgresql://localhost:5432/intercore
spring.datasource.username: postgres
spring.datasource.password: "@ncHocl&ffkfp)h"
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl: true
spring.jpa.show-sql: true